Traceback (most recent call last):
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/chsu/mambaforge/envs/cefibook/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds = e.to_xarray()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/erddapy/url_handling.py:15[0m, in [0;36m_urlopen[0;34m(url, auth, **kwargs)[0m
[1;32m     14[0m [38;5;28;01mtry[39;00m:
[0;32m---> 15[0m     [43mresponse[49m[38;5;241;43m.[39;49m[43mraise_for_status[49m[43m([49m[43m)[49m
[1;32m     16[0m [38;5;28;01mexcept[39;00m requests[38;5;241m.[39mexceptions[38;5;241m.[39mHTTPError [38;5;28;01mas[39;00m err:

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/requests/models.py:1021[0m, in [0;36mResponse.raise_for_status[0;34m(self)[0m
[1;32m   1020[0m [38;5;28;01mif[39;00m http_error_msg:
[0;32m-> 1021[0m     [38;5;28;01mraise[39;00m HTTPError(http_error_msg, response[38;5;241m=[39m[38;5;28mself[39m)

[0;31mHTTPError[0m: 500 Server Error:  for url: https://coastwatch.pfeg.noaa.gov/erddap/griddap/jplAmsreSstMon.nc?tos%5B(2010-12-16T12:00:00Z):1:(2010-12-16T12:00:00Z)%5D%5B(-60):1:(60)%5D%5B(1.0):1:(360.0)%5D,tosNobs%5B(2010-12-16T12:00:00Z):1:(2010-12-16T12:00:00Z)%5D%5B(-60):1:(60)%5D%5B(1.0):1:(360.0)%5D,tosStderr%5B(2010-12-16T12:00:00Z):1:(2010-12-16T12:00:00Z)%5D%5B(-60):1:(60)%5D%5B(1.0):1:(360.0)%5D

The above exception was the direct cause of the following exception:

[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m ds [38;5;241m=[39m [43me[49m[38;5;241;43m.[39;49m[43mto_xarray[49m[43m([49m[43m)[49m

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/erddapy/erddapy.py:614[0m, in [0;36mERDDAP.to_xarray[0;34m(self, **kw)[0m
[1;32m    612[0m response [38;5;241m=[39m [38;5;124m"[39m[38;5;124mnc[39m[38;5;124m"[39m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mprotocol [38;5;241m==[39m [38;5;124m"[39m[38;5;124mgriddap[39m[38;5;124m"[39m [38;5;28;01melse[39;00m [38;5;124m"[39m[38;5;124mncCF[39m[38;5;124m"[39m
[1;32m    613[0m url [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_download_url(response[38;5;241m=[39mresponse)
[0;32m--> 614[0m nc [38;5;241m=[39m [43m_nc_dataset[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mauth[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mauth[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrequests_kwargs[49m[43m)[49m
[1;32m    615[0m [38;5;28;01mreturn[39;00m xr[38;5;241m.[39mopen_dataset(xr[38;5;241m.[39mbackends[38;5;241m.[39mNetCDF4DataStore(nc), [38;5;241m*[39m[38;5;241m*[39mkw)

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/erddapy/netcdf_handling.py:16[0m, in [0;36m_nc_dataset[0;34m(url, auth, **requests_kwargs)[0m
[1;32m     13[0m [38;5;250m[39m[38;5;124;03m"""Return a netCDF4-python Dataset from memory and fallbacks to disk if that fails."""[39;00m
[1;32m     14[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnetCDF4[39;00m [38;5;28;01mimport[39;00m Dataset
[0;32m---> 16[0m data [38;5;241m=[39m [43murlopen[49m[43m([49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[43mauth[49m[38;5;241;43m=[39;49m[43mauth[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mrequests_kwargs[49m[43m)[49m
[1;32m     17[0m [38;5;28;01mtry[39;00m:
[1;32m     18[0m     [38;5;28;01mreturn[39;00m Dataset(Path(urlparse(url)[38;5;241m.[39mpath)[38;5;241m.[39mname, memory[38;5;241m=[39mdata[38;5;241m.[39mread())

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/erddapy/url_handling.py:28[0m, in [0;36murlopen[0;34m(url, auth, **kwargs)[0m
[1;32m     22[0m [38;5;250m[39m[38;5;124;03m"""Thin wrapper around requests get content.[39;00m
[1;32m     23[0m 
[1;32m     24[0m [38;5;124;03mSee requests.get docs for the `params` and `kwargs` options.[39;00m
[1;32m     25[0m 
[1;32m     26[0m [38;5;124;03m"""[39;00m
[1;32m     27[0m [38;5;66;03m# Ignoring type checks here b/c mypy does not support decorated functions.[39;00m
[0;32m---> 28[0m data [38;5;241m=[39m [43m_urlopen[49m[43m([49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[43mauth[49m[38;5;241;43m=[39;49m[43mauth[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m  [38;5;66;03m# type: ignore[39;00m
[1;32m     29[0m data[38;5;241m.[39mseek([38;5;241m0[39m)
[1;32m     30[0m [38;5;28;01mreturn[39;00m data

File [0;32m~/mambaforge/envs/cefibook/lib/python3.10/site-packages/erddapy/url_handling.py:17[0m, in [0;36m_urlopen[0;34m(url, auth, **kwargs)[0m
[1;32m     15[0m     response[38;5;241m.[39mraise_for_status()
[1;32m     16[0m [38;5;28;01mexcept[39;00m requests[38;5;241m.[39mexceptions[38;5;241m.[39mHTTPError [38;5;28;01mas[39;00m err:
[0;32m---> 17[0m     [38;5;28;01mraise[39;00m requests[38;5;241m.[39mexceptions[38;5;241m.[39mHTTPError([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mresponse[38;5;241m.[39mcontent[38;5;241m.[39mdecode()[38;5;132;01m}[39;00m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m     18[0m [38;5;28;01mreturn[39;00m io[38;5;241m.[39mBytesIO(response[38;5;241m.[39mcontent)

[0;31mHTTPError[0m: Error {
    code=500;
    message="Internal Server Error: There was a (temporary?) problem.  Wait a minute, then try again.  (In a browser, click the Reload button.)
(ERROR from data source: java.lang.RuntimeException: ERROR in getPrimitiveArrays for query=?tos%5B102:102%5D%5B30:150%5D%5B0:359%5D
Cannot invoke \"String.indexOf(String)\" because \"<parameter1>\" is null)
(Cause: java.lang.RuntimeException: ERROR in getPrimitiveArrays for query=?tos%5B102:102%5D%5B30:150%5D%5B0:359%5D
Cannot invoke \"String.indexOf(String)\" because \"<parameter1>\" is null)";
}

HTTPError: Error {
    code=500;
    message="Internal Server Error: There was a (temporary?) problem.  Wait a minute, then try again.  (In a browser, click the Reload button.)
(ERROR from data source: java.lang.RuntimeException: ERROR in getPrimitiveArrays for query=?tos%5B102:102%5D%5B30:150%5D%5B0:359%5D
Cannot invoke \"String.indexOf(String)\" because \"<parameter1>\" is null)
(Cause: java.lang.RuntimeException: ERROR in getPrimitiveArrays for query=?tos%5B102:102%5D%5B30:150%5D%5B0:359%5D
Cannot invoke \"String.indexOf(String)\" because \"<parameter1>\" is null)";
}


